services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    environment:
      - WATCHTOWER_CLEANUP=true    # Remove old images after updating
      - WATCHTOWER_POLL_INTERVAL=86400 # Check for updates every 24 hours (default is 86400)
      - WATCHTOWER_INCLUDE_STOPPED=false # Only update running containers
      - WATCHTOWER_NOTIFICATIONS=shoutrrr # Enable notifications (if needed)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Allow Watchtower to manage other containers